### ISSUE TITLE
nadya_issue

### ISSUE THREAD

**Issue by elizarpif** [elizarpif/graph-laba#8]
* сохранить граф из выбранной вкладки в файл как изображение.
* из матрицы составить граф
* читать файлы все форматов (в файле могут быть комментарии начинающиеся с %.)
* матрицу записать на табличку
* стандартные диалоги закрытия/сохранения

**Comment by ProshNad** [comment]
* убрать видимость кнопок изменения размерности таблицы до создания первого графа
